import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";import "../../styles/globals.css";
import Sidebar from "../../components/sidebar/sidebar"; 


const geistSans = Geist({
  subsets: ['latin'], 
  variable: '--font-geist-sans' 
});

const geistMono = Geist_Mono({
  subsets: ['latin'], 
  variable: '--font-geist-mono' 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className={geistSans.className}>
        <div className="flex h-screen bg-background text-foreground"> 
          <Sidebar />
          <main className="flex-1 overflow-y-auto pl-20">
            <div className="p-6">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}